name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane swiftLintLane

  build:
    needs: swiftlint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  pods:
    needs: swiftlint
    runs-on: macos-latest
    steps:
    - name: Install Bundle
      run: bundle install
    - name: Run pods
      run: bundle exec fastlane cocoapodsLane
      
  test:
    needs: swiftlint
    runs-on: macos-latest
    steps:
    - name: Install Bundle
      run: bundle install
    - name: Run pods
      run: bundle exec fastlane xcTestLane
