name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Bundle
        run: bundle install

      - name: Run swiftlint
        run: bundle exec fastlane swiftLintLane

      - name: Build
        run: bundle exec fastlane buildLane
